// https://www.w3.org/2019/wot/json-schema#interpreting-json-schema-as-json-ld-1-1
export default {
  "@version": 1.1,
  xsd: "http://www.w3.org/2001/XMLSchema#",
  "@vocab": "https://www.w3.org/2019/wot/json-schema#",
  id: { "@id": "@id" },
  type: { "@id": "@type" },
  object: "ObjectSchema",
  array: "ArraySchema",
  boolean: "BooleanSchema",
  string: "StringSchema",
  number: "NumberSchema",
  integer: "IntegerSchema",
  null: "NullSchema",
  properties: {
    "@container": "@index",
    "@index": "propertyName",
  },
  items: { "@type": "@vocab" },
  oneOf: { "@type": "@vocab", "@container": "@set" },
  allOf: { "@type": "@vocab", "@container": "@set" },
  anyOf: { "@type": "@vocab", "@container": "@set" },
  minItems: { "@type": "xsd:decimal" },
  maxItems: { "@type": "xsd:decimal" },
  minimum: { "@type": "xsd:decimal" },
  maximum: { "@type": "xsd:decimal" },
  enum: { "@container": "@set", "@type": "@json" },
  writeOnly: { "@type": "xsd:boolean" },
  readOnly: { "@type": "xsd:boolean" },
  format: { "@type": "xsd:string" },
  required: { "@type": "xsd:string", "@container": "@set" },
  title: { "@type": "xsd:string" },
  description: { "@type": "xsd:string" },
};
